export const TYPE_MATERIAL = 'TypeMaterial'
export const COLLECTION_OBJECT = 'CollectionObject'
export const ASSERTED_DISTRIBUTION = 'AssertedDistribution'
export const GEOREFERENCE = 'Georeference'
export const AGGREGATE = 'Aggregate'
export const OTU = 'Otu'
