taxa_page:
  overview:
    panels:
      - - - id: panel:gallery-v2
            bind:
              subMaxImages: 11
          - panel:descendants
          - panel:nomenclature
          - panel:nomenclature-references
          - panel:type
          - panel:type-specimen

        - - panel:map-v2
#         - panel:map
          - panel:content
          - panel:keys
          - panel:statistics
          - panel:sounds

      - - - id: panel:biological-associations-v2
            bind:
              collapseAboveRank: 'SpeciesGroup'
              collapseThreshold: 15

  specimen_records:
    label: 'Specimen & Occurrence Records'
    rank_group: ['SpeciesGroup', 'GenusGroup']
    panels:
      - - - panel:specimen-occurrences

  asserted_distributions:
      label: 'Asserted Distributions'
      rank_group: ['SpeciesGroup']
      panels:
      - - - panel:asserted-distributions

  inaturalist:
    label: 'iNaturalist'
    panels:
      - - - id: panel:inaturalist

  GBIF:
    label: 'GBIF'
    panels:
      - - - panel:gbif-taxon
          - panel:gbif-images
          - panel:gbif-map
          - panel:gbif-type-specimens

